features:
  scss:
    enabled: true
    minify:  true
    autoprefix:
      enabled: true
      settings:
        browsers:
          - last 5 versions
  js:
    enabled:    true
    browserify: true
    minify:     true
  jekyll:
    enabled: true
  notifications:
    enabled: true
  serve:
    port:    8080
    enabled: true

paths:
  source:
    scss:   _assets/scss
    js:     _assets/js
    images: _assets/images
    fonts:  _assets/fonts
  destination:
    scss:   assets/css
    js:     assets/js
    images: assets/images
    fonts:  assets/fonts
  jsBundles:
    - app.js
